#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@15.164.250.198:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Summernote
#  summernote:
#    image:
#      upload-dir: /Users/hyun/uploads

  #kakao OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7d1b8d2a934aea81ad94f34bb0bee10c
            redirect-uri: "http://localhost:10000/member/kakao-login"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#  app:
#    file:
#      upload-dir: /Users/hyun/uploads

  # 이미지 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

#      location: c:\\upload
      location: /Users/hyun/uploads
      enabled: true

  session:
    store-type: redis


